Repository googleapis/nodejs-workflows, pull requests merged in 2020-11, with the labels that each got.

#18 build: sync latest protos and build files
  .github/workflows/ci.yaml
  .jsdoc.js
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CODE_OF_CONDUCT.md
  linkinator.config.json
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
Labels: cla: yes, context: partial

#19 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#20 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1beta/executions_client.ts
  src/v1beta/workflows_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: workflows, automerge, cla: yes

#23 fix: better fallback feature detection, jsdoc update
  protos/protos.json
  src/v1beta/executions_client.ts
  src/v1beta/workflows_client.ts
  synth.metadata
Labels: api: workflows, cla: yes, context: none

#25 build: stop tracking files
  src/v1beta/executions_client.ts
  synth.metadata
Labels: api: workflows, cla: yes, context: none

#26 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: workflows, automerge, cla: yes, context: full
