Repository googleapis/nodejs-workflows, pull requests merged in 2021-05, with the labels that each got.

#46 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: workflows, automerge, cla: yes, context: full

#48 fix(deps): require google-gax v2.12.0
  package.json
Labels: api: workflows, automerge, cla: yes

#54 feat: update release level to GA
  .repo-metadata.json
  README.md
Labels: api: workflows, cla: yes

#63 chore: remove synth.* because this repo was already migrated to owl bot
  synth.metadata
  synth.py
Labels: api: workflows, cla: yes
